# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd569e09d4b970c0b24736e40e6ea13389f31739a149ff2b0c50c527a611db003aed156267199c36ca58e8cc5f8752fa8d553498f967be0d939848cfd9acb756

test:
  secret_key_base: de2bb4b1d058bb1ea9bc7603ac378def0af0160fefb538ca36bdb30327ba676947d84e3dea064d24abab3c426a8d33aa6f60789229beb4446b062fa50e590075

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
